[WIP] イベント一覧ページ（参加しているイベントのみ）
nocox/asakatu-kun pull request #203
Opened 2019-11-18 23:17 UTC by projectormato

## Issue番号
fix: #144 

## 実装の目的/背景
ログインユーザが参加しているイベントだけを表示します

## 概要

## 動作確認方法(チェック項目)
- [ ]

## レビューポイント
-

## 留意事項
-

## 残課題
-

2019-11-19 23:12 UTC, projectormato commented
大体同じように実装したんだけど、「参加イベント」をクリックした時に
```
TypeError: "state.joinedEventList is undefined"
    joinedEventList Events.vue:57
    mappedState vuex.esm.js:836
    VueJS 4
    render Events.vue:37
```
が出て表示されない...どこか抜けている気がするけど分からない、ヘルプミー！

2019-11-20 00:10 UTC, yukikom-biz requested changes

2019-11-20 00:10 UTC, yukikom-biz commented on springboot/src/main/java/com/asakatu/response/ForFrontEvent.java
>  // フロントのための整形されたEventClassです。追加したい情報があったらこちらへ
ここは改修対象ファイルですね。
#199

2019-11-20 00:10 UTC, yukikom-biz commented on vue/src/components/eventList/EventList.vue
> +            </router-link>
`vue/src/components/eventList/EventList.vue`
ここの変更消えてたんだけど、こんな感じにして欲しいっす

2019-11-20 00:10 UTC, yukikom-biz commented on vue/src/components/eventList/detail/eventCard.vue
>                  <p class="startDate">{{}}</p>
この辺り日付データの整形をしなければいけませんね。

2019-11-20 00:14 UTC, yukikom-biz requested changes
これが原因ですね。

2019-11-20 00:14 UTC, yukikom-biz commented on vue/src/views/Events.vue
> +                joinedEventList: state => state.joinedEventList.eventList,
`joinedEventList: state => state.eventList.joinedEventList`
こうですね。
`eventList.js`の中の`joinedEventList`なので

2019-11-20 00:15 UTC, yukikom-biz commented
あ、やばい。会社のアカウントでコメントしてしまった。
まぁ良いか

2019-11-20 00:16 UTC, yukikom-biz commented on vue/src/components/eventList/EventList.vue
> +            </router-link>
値渡す処理も書いておいて笑

2019-11-20 00:16 UTC, Yuki-k-lion commented
アカウント変えた。

2019-11-20 00:17 UTC, yuki-koma2 requested changes
上記コメントしたとこ直してくれれば、とりあえずOKだと思います。
（バックエンドは正直ちゃんとはみてない。ちゃんとみるとリファクタしたくなってしまう笑）

2019-11-20 11:17 UTC, projectormato commented on vue/src/views/Events.vue
> +                joinedEventList: state => state.joinedEventList.eventList,
これ考えてやってみたけど、ほんと...？
`state.eventList.eventList`なのは、eventList.jsの中の`eventList`stateだからじゃなくて、
`eventList`stateの`eventList`って項目だからじゃないかな...

2019-11-20 11:59 UTC, Yuki-k-lion commented on vue/src/views/Events.vue
> +                joinedEventList: state => state.joinedEventList.eventList,
`src/store/index.js`

2019-11-20 12:27 UTC, projectormato commented on vue/src/views/Events.vue
> +                joinedEventList: state => state.joinedEventList.eventList,
修正しました！
https://github.com/nocox/asakatu-kun/pull/203/commits/e3e096229a3388196fd0f1d2d3603e3ae83b7845

2019-11-20 12:27 UTC, projectormato commented on vue/src/components/eventList/EventList.vue
> +            </router-link>
修正しました！
https://github.com/nocox/asakatu-kun/pull/203/commits/444f41ad7e6e5140faae7c10da742be661e97bb9

2019-11-20 12:28 UTC, projectormato commented on vue/src/components/eventList/detail/eventCard.vue
>                  <p class="startDate">{{}}</p>
修正しました！
https://github.com/nocox/asakatu-kun/pull/203/commits/f71da417dcea11d592ec1ab73e6d1ace02a6b4b2

2019-11-20 12:31 UTC, projectormato commented
イベント0件の時何も表示されないだけでした！(500エラーは返らない)

2019-11-20 12:49 UTC, yuki-koma2 approved these changes
動き確認してないけど、コード的には。LGTM

あとでリファクタしたいな、ってとこだけコメントしました。
リリース後にどうにかします。

2019-11-20 12:49 UTC, Yuki-k-lion commented on vue/src/components/eventList/EventList.vue
> +        <p>-----------------------------</p>
この線はまーじぱいせんにいい感じに消してもらおう。笑

2019-11-20 12:49 UTC, Yuki-k-lion commented on vue/src/components/eventList/detail/eventCard.vue
> +                    <span class="weekDay">{{ designDate.split("(")[1].split(")")[0] }}曜日</span>
関数化したほうがわかりやすい気はするけど、
一旦これで行きましょうか。
スピード重視！

2019-11-20 12:49 UTC, Yuki-k-lion commented on vue/src/components/eventList/detail/eventCard.vue
> +                    <span class="weekDay">{{ designDate.split("(")[1].split(")")[0] }}曜日</span>
あとでリファクタします。

2019-11-20 12:50 UTC, Yuki-k-lion commented on vue/src/components/eventList/detail/eventCard.vue
> +                    <span class="weekDay">{{ designDate.split("(")[1].split(")")[0] }}曜日</span>
Utilsみたいなフォルダを作って、そこにちょっとした処理まとめたい気持ち

2019-11-20 12:51 UTC, projectormato commented on vue/src/components/eventList/detail/eventCard.vue
> +                    <span class="weekDay">{{ designDate.split("(")[1].split(")")[0] }}曜日</span>
全面的にめっちゃ分かる

2019-11-20 12:52 UTC, projectormato commented on vue/src/components/eventList/EventList.vue
> +        <p>-----------------------------</p>
そうね、線あったほうが区切り分かりやすいかなって

2019-11-21 11:08 UTC, projectormato commented
![LGTM](https://lgtmoon.herokuapp.com/images/35834)

2019-11-21 11:08 UTC, merged